blake2b-ref.c
Fixes old compilers like gcc 2.95.3. Yes some people are still using it.
=> blake2b-ref: Separate declaration and code

rdiff.c
Patch by Daniel Baumann <daniel@debian.org> for librsync >= 0.9.7, which makes rdiff aware of -i and -z getopt options mentioned in --help output. For further information, please have a look to Debian bug ID #435894 at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=435894
=> Unknown rdiff options -i and -z

NEWS, delta.c, librsync.h, search.c
It is not clear in the header file that rs_build_hash_table() MUST be
called after the signature has been loaded.
=> Add comments and asserts regarding rs_build_hash_table()

.travis.yml, CMakeLists.txt, NEWS.md, doc/install.md
I've tweaked the build process a bit. I have the need to minimize build dependencies, and so I made the following changes:
* Added an option (default ON) to build the `rdiff` target;
* Added an option (default OFF) to build with compression support;
* Made `zlib` and `bzip2` libraries optional.
This allows me to build only the `rsync` library (and not `rdiff`), and thus avoid having `popt` dependency. Moreover, `zlib` and `bzip2` use can be disabled.
The removal of `REQUIRED` attribute in `find_package` turns an hard error in a soft one, and does not stop the generation step. This allows the user to tweak parameters after generation with CMake.
The compression support is not implemented for now, so I've kept it OFF by default. When the support is present, you can make the option ON by …
=> Build rdiff target optionally

src/version.c
Removed `librsync.h` include from `version.c`. The build was failing
because `stdlib.h` include was missing, and so `size_t` type not found.
There were two options to fix that: either remove `librsync.h` include,
or add also `stdlib.h` include. Since they were both not used by
`version.c`, I've chosen to remove them.
=> Fixed MSVC build under Windows

src/patch.c
I found useless allocations in the execution of COPY command, in the context of patch application.
The program flow was basically this:
* allocate a buffer that fits within the output buffer (`patch.c:225`);
* pass that to the copy callback (`patch.c:227`);
* the callback is free to use another buffer if she wants (documentation of `rs_copy_cb` at `librsync.h:528`);
* copy the buffer (the one used by the callback) to the output buffer;
* free the allocated buffer.
I've changed the flow in this way:
* allocate nothing!
* pass the output buffer directly to the copy callback; this is safe, since the previously allocated buffer was no bigger than the output buffer (see `patch.c:217`);
* the callback is still free to use another buffer;
* copy the buffer to the output buffer if the callback …
=> Avoid useless allocation in COPY command

src/fileutil.c, tests/triple.test
As part of realloc patch, I wrote a test for rdiff using pipes. I discovered a CRITICAL problem! On Windows ALL output written to stdout has LF changed to CRLF. This CORRUPTS binary data and all signatures and deltas written to stdout are wrong!
Since this test was not running, I also added a quick fix for issue #71
=> Open stdout and stdin in _O_BINARY mode on Windows.

CMakeLists.txt
This is a mistake in my previous mingw patch. I noticed my Centos6 64-bit supports fseeko64, but fails off64_t size check. It does compile for some reason in the end, but it's an inconsistency. fseeko is preferred to fseeko64 in buf.c, let's not declare off64_t if it isn't found.
=> Check that off64_t exists before declaring it as RS_LONG_T.

src/checksum.c, src/checksum.h, src/librsync.h, src/mksum.c
In checksum.c make rs_calc_weak_sum() use the implementation in
rollsum.[hc]. Tidy checksum.h removing now unused RS_CHAR_OFFSET.
In librsync.h change rs_weak_sum_t from "unsigned int" to uint32_t.
In mksum.c use rs_weak_sum_t instead of "unsigned int" as the type of
a calculated weaksum.
=> Tidy rs_weak_sum_t related code.

CMakeLists.txt, src/rollsum.c, src/rollsum.h, tests/rollsum_test.c
The char offsets in the rollsum don't need to be added incrementally, but can be calculated and added once.
=> Optimize rollsum.c to add char offsets once.

tests/mutate.test
A tiny deficiency in one of the tests I noticed... it's not actually excercising all the different hashopts it's supposed to.
=> Fix mutate.test to actually use the hashopt args.

.gitignore, CMakeLists.txt, src/delta.c, src/job.c, src/job.h, src/mksum.c, src/readsums.c, src/search.c, src/sumset.c, src/sumset.h, src/util.c, src/util.h, src/whole.c, tests/sumset_test.c, tests/triple.test
This makes `rs_signature_t` more like a class with methods for interacting with it.
This removes some redundant code that duplicated things like signature sanity checking and strongsum algorithm selection based on the signature magic. This makes the sanity checking way more consistent and will make it easier to add different checksum and rollsum algorithms or hashtable implementations.
Removes `job->estimated_signature_count` and renames `job->sig_file_bytes` to `job->sig_fsize`. The estimated block count is is redundant with file size for estimating the number of blocks to pre-allocate. Moves the calculation of block count into `rs_signature_init()` method which takes an `sig_fsize` argument. Note this is also not exposed at the API, so can only be used for whole file operations.
Changes …
=> Tidy signature handling code.

doc/Doxyfile.in, src/delta.c, src/hashtable.c, src/hashtable.h, src/sumset.c, src/sumset.h, tests/hashtable_test.c
This shaves about 10~15% off the delta execution time, winning back the tiny performance losses we got for small files when we switched to the new open addressing hashtable.
The commit history shows the incremental refinements made. Interestingly the change from function pointers to directly referenced functions made nearly zero difference, which surprised me. The big wins were in making things static inline, with an early small win for changing the probing to a for loop that doesn't check for looping through all elements, instead relying on hashtable_add() to always leave one empty bucket.
It now is effectively a template/parametric class implemented using preprocessor macros, which is pretty much the only way to make it possible to static inline all the hashtable_find() related calls …
=> Optimize and refine hashtable.

src/librsync.h
Include what you use: librsync.h uses FILE struct, but did not #include <stdio.h> to import the symbol.
=> #include <stdio.h> in librsync.h

src/delta.c, src/librsync.h, src/whole.c, src/whole.h
In delta.c make the max miss output length 4*block_len  instead of rs_outbuflen so that it's independent of the whole file API buffer length arguments.
In whole.[ch] make rs_inbuflen and rs_outbuflen default to zero which means use recommended buffer sizes for the operations being performed. Make all the whole file operations use recommended buffer sizes for the operation being performed unless the rs_inbuflen or rs_outbuflen overrides have been set.
This makes rdiff use more efficient buffer sizes by default when --input-size and --output-size arguments are not set.
=> Improve default buffer sizes used.

src/hashtable.h, src/sumset.c, tests/hashtable_test.c
A large number of duplicate blocks (eg long runs of zero) act like a DOS attack on the open addressing hashtable because they all cluster.
This means we only keep the first copy of duplicate blocks in the hashtable, and thus matches in the delta will always refer to the first matching block.
This does mean we can't return a single long match for a long sequence of identical blocks, and instead will return multiple single block matches against the first block. However, that's what we currently do anyway since we only find the first matching block in the hashtable even if there are multiple identical blocks in there.
It's also debatable if a single long match of multiple identical blocks is more efficient than multiple small matches against the first block. The delta might be a little …
=> Don't add duplicate blocks to the hashtable.

CMakeLists.txt, src/blake2-impl.h, src/blake2.h, src/blake2b-ref.c, src/config.h.cmake
This updates to the latest BLAKE2 reference implementation from https://github.com/BLAKE2/BLAKE2.
Note this appears to fix #103 and hopefully will fix #25.
I will need someone experiencing #25 to test if this fixes it, since I don't have a big-endian platform to test it on.
=> Update blake2 from upstream and improve cmake endian checking.

CMakeLists.txt
By default, CMake assumes that the project is using both C and C++.  By
explicitly passing 'C' as argument of the project() macro, we tell CMake
that only C is used, which prevents CMake from erroring out if a C++
compiler doesn't exist.
=> CMakeLists.txt: Don't require a C++ compiler

NEWS.md, src/mksum.c, src/scoop.c, src/tube.c, tests/largefile.test
Fix scoop.c and mksum.c handling of truncated input to correctly terminate with RS_INPUT_ENDED. This means rdiff will correctly return an error message instead of hanging for any type of operation that hits an unexpected EOF.
Add small optimizations to scoop.c and tube.c input handling.
Remove input and output size arguments for rdiff delta operation from largefile.test to test the now sane default values.
Update NEWS.md with this and all other missing changes ready for the v2.0.1 release.
=> Fix #32 hang for truncated input.

NEWS.md, src/job.c, src/job.h, src/tube.c
This fixes #33 and tidies up and optimizes the rs_job_iter() code.  It removes code checking for programming errors and replaces them with more extensive precondition asserts.
I also slightly cleaned and optimized rs_tube_catchup() when there is nothing to catchup.
It also includes changing rs_job_check() from a function to a #define so it gets completely optimized away when debugging is turned off and more clearly indicates where the job was bad when asserts fail.
=> Fix #33 rs_job_iter needs calling twice with eof=1.

cmake/FindPOPT.cmake
Previously it was incorrectly marking the non-existent POPT_INCLUDES as advanced.
This ensures that ccmake doesn't list POPT_INCLUDE_DIRS as a configurable option.
=> Fix cmake/FindPOPT.cmake to mark_as_advanced POPT_INCLUDE_DIRS

NEWS.md, src/emit.c
Replace unnecessary fs_fatal() calls in emit.c with asserts.
These errors could only happen if rs_int_len() was broken, so don't
need runtime checks, asserts are sufficient.
This also involved slighly changing the logic to avoid compiler
warnings when assserts are omitted for release builds, which also made
the code a little more consistent.
The only rs_fatal() calls left are for alloc failures, the tube "popping", netint.c encountering a >64bit int file offset or size, and delta.c failing a paranoid weaksum check with the rdiff --paranoia checking.
=> Fix #55 remove excessive rs_fatal() calls.

src/delta.c, tests/largefile.test
Change the max miss size to 32K from 4*block_len.
This gives a constant 0.01% 3 command bytes overhead for misses. For small block sizes it has nearly no impact on performance but gives slightly smaller deltas. For large block sizes it gives a tiny performance increase and significantly reduced memory requirements for deltas.
Also add extra block size argument to largefile.test to make it easy to test the impact for different block sizes.
This had less performance impact than I expected, but it is a little win.
=> Tune max miss size for deltas.

CMakeLists.txt
Using check_c_source_runs() causes the build to fail when cross compiling. In that case we cannot check for printf "%zu" size_t formating support by executing a binary - instead assume it.
This should be safe as AFAIK only MS Visual Studio versions prior to VS2013 doesn't support it, and it's unlikely that someone should be using an old Visual Studio to cross compile librsync.
=> Avoid check_c_source_runs() when cross compiling

NEWS.md, src/sumset.c
Fix rs_block_sig_size() for correct memory alignment when packing rs_block_sum_t instances in rs_signature_t instances.
Update NEWS.md with all changes since release of v2.0.1.
=> Fix #135 memory alignment for rs_block_sum_t instances.

NEWS.md, src/hashtable.h, tests/hashtable_test.c
Rename key/entry/match/hashtable to mykey/myentry/mymatch/myhashtable in test and header docstrings. This reduces the chance of a collision and makes it clearer these names are arbitrary.
=> Fix #134 hashtable_test.c name collision for key_t.

CMakeLists.txt, src/buf.c, src/checksum.c, src/command.h, src/delta.c, src/hashtable.h, src/job.h, src/librsync.h, src/mdfour.c, src/mksum.c, src/netint.c, src/patch.c, src/rdiff.c, src/scoop.c, src/stream.c, src/sumset.h, src/trace.c, src/trace.h, src/tube.c
Unfortunately indent's comment reformatting with -fca is not consistent, giving different results with repeated runs on the same input.
This removes the -fca argument from the make tidy target so that it doesn't introduce spurious comment changes every time it's run. If you really want to reformat comments use 'make tidyc', since tidyc now includes workarounds to make it consistent.
Reformat all the code again using 'make tidyc' using the latest tidyc with the consistency fix in it.
=> Fix 'make tidy' and 'make tidyc' to be consistent.

src/sumset.c
I noticed that there was a memory leak on rs_job_iter, after investigating I found that it was not freeing memory hold by `rs_signature_t->block_sigs`. 
This patch fixed the memory leak.
=> Fix memory leak on signature->block_sigs

.gitignore, CONTRIBUTING.md, src/buf.c, src/command.h, src/delta.c, src/emit.c, src/emit.h, src/hashtable.h, src/job.c, src/job.h, src/librsync.h, src/mdfour.c, src/mksum.c, src/msg.c, src/netint.c, src/prototab.c, src/prototab.h, src/rdiff.c, src/readsums.c, src/scoop.c, src/stats.c, src/stream.c, src/trace.c, src/trace.h, src/tube.c
This fixes some minor doxygen errors and warnings. The example generated docs can be seen at;
http://minkirri.apana.org.au/~abo/librsync
Running `make doc` is now completely error and warning free.
=> Fix up doxygen comments.

CONTRIBUTING.md
This updates the documentation of the release process to make it clearer how
to do this on github, and adds a step that ensures the release has a stable
tarball snapshot that is not going to change.
=> Fix #146 Update release process to include stable tarballs.

NEWS.md, src/delta.c, src/librsync.h, src/rdiff.c
This feature is redundant and broken, and is now causing more bugs than it is uncovering. Removing it.
This fixes #155 and simplifies the code a bit.
Also update NEWS.md with all changes since v2.0.2.
=> Fix #155 remove redundant and broken `--paranoia` option from rdiff.

CMakeLists.txt, NEWS.md, src/librsync.h, src/librsync_export.h, src/rdiff.c
This sets rsync_EXPORTS on Windows to prevent build failure. In addition, missing LIBRSYNC_EXPORT types are added to certain variables in librsync.h to prevent redefiniton errors on MSVC, and dlls are correctly installed into the bin directory.
=> fix build on MinGW-w64 and MSVC

doc/Doxyfile.in, src/hashtable.c, src/hashtable.h, tests/hashtable_test.c
This simplifies the macro usage in hashtable.h to be less confusing and auto-format better.
It also adds support for turning off the mix32() finalizer, which is not necessary if your hash function already has good distribution characteristics (like RabinKarp does).
=> Tidy hashtable.[ch] and make use of mix32() on hash keys optional.

NEWS.md, src/fileutil.c, src/librsync.h, src/sumset.c, tests/sumset_test.c
Change rs_file_size() to return -1 for unknown file sizes and update docstring in librsync.h. In sumset.c update rs_signature_init() work correctly for sig_fsize<12.
Update sumset_test.c to use -1 for unknown filesizes and add some tests for checking invalid blake2 strong_len arguments.
=> Use -1 for "unknown" for file sizes.

.travis.yml, CMakeLists.txt, NEWS.md
BUILD_SHARED_LIBS defaults to ON, and can be set to OFF using `ccmake .` to
build librsync as a static library.
=> Add cmake BUILD_SHARED_LIBS option for static library support.

.gitignore, src/hashtable.h
The Visual Studio C++ compiler seems not to like the current implementation of the `_KEY_HASH` macro. This pull request is aimed to restore compatibility with Microsoft Visual Studio 2019.
In addition, some wildcards are added to `.gitignore` targeting output files from CMake and from the build.
=> fix compilation with MS Visual Studio ad ignore build files

NEWS.md, src/netint.c
This reverts this to what it was before, with some minor tidy ups. I believe
that this is pretty much the only way to make it work when rs_long_t is of an
unknown size. It's also pretty hard to write tests that will still pass on
platforms where rs_long_t is less than 64bits.
=> Fix #176 rs_int_len() for large values.

CMakeLists.txt
The librsync code uses some C99 constructs, but old compilers such
as gcc 4.7 don't default to -std=c99. This commit makes sure librsync
is built with -std=gnu99.
Fixes:
src/rabinkarp.h:82:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
for (size_t i = len; i; i--) {
^
src/rabinkarp.h:82:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
=> CMakeLists: fix build with old compilers

CMakeLists.txt, src/netint.c, src/netint.h, src/tube.c, tests/netint_test.c
Add tests/netint_test.c and CMakeLists.txt changes to test rs_int_len().
In netint.[ch] replace runtime checks for invalid arguments with assert()
statements and tidy the argument names, variable names, and ordering. Replace
`unsigned char` arguments with `rs_byte_t`. Add an assert to rs_int_len() to
require the argument is positive.
Simplify and tidy tube.c, making variable names and code structure more consistent. Replace a fatal runtime check that should never happen with an assert().
=> Simplify and tidy netint.[ch], tube.c and add netint tests.

src/hashtable.h
Tiny delete of typo duplicate #define/#undef for `NAME_new`.
=> Remove duplicated #define/#undef for `NAME_new`.

cmake/FindPOPT.cmake
Add PkgConfig support to retrieve popt dependencies otherwise static
build can fail if popt has been linked with iconv:
```
[100%] Linking C executable rdiff
/home/buildroot/autobuild/instance-2/output-1/per-package/librsync/host/opt/ext-toolchain/bin/../lib/gcc/powerpc-buildroot-linux-uclibc/8.3.0/../../../../powerpc-buildroot-linux-uclibc/bin/ld: /home/buildroot/autobuild/instance-2/output-1/per-package/librsync/host/powerpc-buildroot-linux-uclibc/sysroot/usr/lib/libpopt.a(poptint.o): in function `POPT_fprintf':
poptint.c:(.text+0x34c): undefined reference to `libiconv_open
```
Fixes:
- http://autobuild.buildroot.org/results/896e8e3efbedad90d66ae8c4e1e50f16206cab49
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> cmake/FindPOPT.cmake: Add PkgConfig support

CMakeLists.txt, cmake/FindPOPT.cmake, src/trace.c
This suppresses some harmless warnings given when compiling on MinGW-w64 due to differences in formatting. It also fixes some "dllimport" warnings and corrects a conditional block in `cmake/FindPOPT.cmake`. 
Fixes #184.
=> fix various warnings

src/buf.c
This commit removes cppcheck "style" warning.
Fixes:
[src/buf.c:104]: (style) Checking if unsigned variable 'len' is less than zero.
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
=> buf: fix usage of size_t

NEWS.md
Update release date in NEWS.md. Note CMakeLists.txt and librsync.spec are
already up to date.
=> Release v2.3.0.

.gitignore, CMakeLists.txt, src/rabinkarp.c, src/rabinkarp.h, tests/rabinkarp_perf.c
This optimizes the rabinkarp_update() by correctly using unsigned constants and manually unrolling the loop for best performance. See the following for analysis that lead to this patch;
https://github.com/dbaarda/librsync-tests/blob/master/RESULTS.rst
=> Optimize rabinkarp_update()

src/hashtable.c, src/hashtable.h
Add a simple/small k=1 bloom filter to the hashtable to reduce hashtable probing (and thrashing cpu memory cache) by more than 50%. It can be turned off by defining HASHTABLE_NBLOOM.
Reduce the max hashtable load factor from 80% to 70% to ensure that most hashtable probing for lookups is within the same 64 byte cache line.
Fix hashcmp_count stats to include comparing against empty buckets. Previously these were not counted, but still required a hashtable lookup. This will increase the hashcmp_count stats compared to previous versions, but with the new bloom filter we avoid many lookups entirely.
Slightly tidy the _for_probe() and _KEY_HASH() macro's using a nozero() static inline to reserve zero entries for empty buckets.
This improves delta performance by between 20%~40%, particularly …
=> Improve hashtable performance.

src/hashtable.c, src/hashtable.h
Use the upper bits of the hash as the bloom filter index instead of using the lower bits used for the hashtable index.
This means we don't use the same index for the bloom filter and hashtable which ensures we don't always start probing the hashtable after bloom-filter hits at known non-empty entries. This is similar to using a "different hash" for each "k" of a bloom filter. The hashtable probes have a chance of immediately hitting an empty entry, significantly reducing the number of weaksum compares.
Also add tmask and bshift attributes to hashtable_t so we don't need to recalculate them for every probe.
=> Make bloom filter more effective.

src/hashtable.h
Use const local variables for the tmask and ktable to avoid dereferencing them from the hashtable with `t->tmask` and `t->ktable` repeatedly in the tight probing loop.
This doesn't make much difference when optimizing gcc with `-O3`, but it does with lower levels of optimizing, and is highly visible when profiling. So this will presumably help a fair bit on platforms that don't have highly optimizing compilers.
=> Optimize _for_probe() using const local variables.

CMakeLists.txt, cmake/FindPOPT.cmake, cmake/Findlibb2.cmake, tests/rdiff_bad_option.sh
This should fix problems on FreeBSD with cmake's popt detection and running tests without needing /bin/bash.
This fixes our cmake/FindPOPT.cmake by copying official FindPackage() examples and following the instructions for correctly using PkgConfig found here;
https://stackoverflow.com/questions/29191855/what-is-the-proper-way-to-use-pkg-config-from-cmake
It also updates cmake/Findlibb2.cmake to follow best practices better, and cleans our FindPackage() handling in CMakeLists.txt.
Finally, it fixes the only test script we had using `#!/bin/bash` to use `#!/bin/sh` instead. Apparently FreeBSD doesn't have bash installed by default, and this script doesn't need bash anyway.
=> Fix #198 and #199 broken cmake popt detection and use /bin/sh not /bin/bash.

NEWS.md, src/patch.c, src/sumset.c, src/trace.h
Fix a bug which would make librsync patch hang for a corrupt delta containing a zero-length copy command. Patch will now fail returning RS_CORRUPT on encountering a zero length copy command.
Make rs_patch_s_copying() do assert() that copy_cb() didn't copy more data than requested so that debug builds highlight this API violation. Keep the backwards-compatible defensive behavior of only copying the amount requested for non-debug builds, but upgrade the (possibly disabled) trace about it to log warning. Fix the rs_trace() of "copy callback returned ..." to only output this trace if the copy_cb() failed.
Tidy rs_patch_s_literal() and rs_patch_s_copy() code for updating stats to make them consistent.
Add rs_warn() to trace.h to make it easier to log warnings.
=> Fix patch bug for zero-length copies and improve bad copy_cb() handling.

src/hashtable.c
kbloom is a bitmask with 'size2' bits, where 'size2' is the next power of 2 of 'size'. Thus, if 'size' is smaller than 4, 'size2' is smaller than 8, so that size2 / 8 == 0 and calloc allocates 0 bytes. This causes heap corruption when kbloom is subsequently written to. See discussion on https://groups.google.com/g/librsync/c/vmqzQS1QjIw.
=> Fix heap corruption from too small kbloom

CMakeLists.txt, cmake/FindLIBB2.cmake
When building this project with CMake (version 3.20.5), I got the following error message:
```
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- ZLIB_INCLUDE_DIRS  = /usr/include
-- ZLIB_LIBRARIES = /usr/lib64/libz.so
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
The package name passed to `find_package_handle_standard_args` (LIBB2) does
not match the name of the calling package (libb2).  This can lead to
problems in calling code that expects `find_package` result variables
(e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
cmake/Findlibb2.cmake:16 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
CMakeLists.txt:183 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
-- …
```
=> cmake: fix warning for later CMake versions

.gitattributes, CMakeLists.txt, cmake/FindPOPT.cmake, tests/delta.test, tests/help.test, tests/largefile.test, tests/mutate.test, tests/performance.test, tests/rdiff_bad_option.sh, tests/signature.test, tests/testcommon.sh, tests/triple.test
This makes all tests pass on Windows when libpopt is installed so rdiff is built and tested. This includes;
* Tidy and simplify cmake/FindPOPT.cmake.
* Fix bash test scripts invoked by cmake to work on Windows.
* Add .gitattributes to ensure test data is binary
Note libpopt is now available on windows in the vcpkg package repository. It can used to compile and test rdiff on Windows like this;
```sh
$ vcpkg --triplet x64-windows install libpopt
$ cmake -B Release -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
$ cmake --build Release --config Release --target check
```
=> Fix bash test scripts to work on Windows.

CMakeLists.txt, cmake/BuildType.cmake
This is an idea taken from the following post;
https://blog.kitware.com/cmake-and-the-default-build-type/
It sets the default build type to Debug for git clone, otherwise the default is Release. It also sets possible values for the cmake-gui or ccmake. It works with multi-config generators and respects values set on the cmdline.
=> Tidy the cmake config and add better build configuration support.

.gitignore
This seems to be produced by some interaction with the LSP:
```
build/.cmake/
└── api
└── v1
├── query
│   └── client-vscode
│       └── query.json
└── reply
├── cache-v2-de8827e00eefbe0ab990.json
├── codemodel-v2-b00616cea6b8f7146a1d.json
├── index-2021-09-07T15-02-32-0670.json
├── target-check-Debug-7dda4a54f0e4766a4e86.json
├── target-checksum_test-Debug-888c1751d218b338829a.json
├── target-clang-tidy-Debug-25483cb1b4dbe3ae1a4c.json
├── target-hashtable_test-Debug-45ccd911814c5a8480e0.json
```
=> Ignore .cmake directory

NEWS.md, src/buf.c, src/delta.c, src/job.c, src/job.h, src/librsync.h, src/mksum.c, src/netint.c, src/patch.c, src/readsums.c, src/scoop.c, src/scoop.h, src/stream.h, src/tube.c, src/whole.c
This means deltas only accumulate data into the scoop buffer if the input stream is too small, otherwise it will process directly from the input stream. If the input stream always has enough input data to progress when calling rs_job_iter(), it will leave an unprocessed "tail" fragment in the input buffer that the caller must shuffle and refill. If there is not enough input data, it will start accumulating the data into the internal scoop buffer instead.
This makes delta calculations 5%~15% faster by avoiding all the data copying into the scoop buffer.
=> Make delta directly process the input stream if it has enough data.

.github/workflows/check.yml, .gitignore
This makes downloadable artifacts out of the whole build tree and install results for every Check run. The build tree is perhaps useful for understanding build failures. The install results gives us compiled binaries and libraries that can be directly installed, which is particularly useful for platforms like Windows.
=> Upload build and install artifacts from Github actions

.github/workflows/check.yml, .github/workflows/lint.yml, CMakeLists.txt, NEWS.md, tests/rabinkarp_perf.c
The old v2 versions of `checkout` and `upload-artifact` github actions now produce errors warning they must be updated. The new versions are v3.
The `iwyu` package has now fixed it's deps and we no longer need to explicitly install `libclang-common-9-dev` which doesn't exist any more.
The `iwyu` build target should ignore `fileutil.c`, and use neater clang output with noisy "note:" output removed.
Run `make iwyu-fix` to fix includes for `tests/rabinkarp_perf.c`.
=> Update github actions and fix `iwyu` build target.

CONTRIBUTING.md, NEWS.md
This ensures we have a compiled win64 release artifact with each release. Also updated NEWS.md to include all pull requests since the last release.
=> Fix #244 Add win32 install artifact to release instructions.

CONTRIBUTING.md, NEWS.md, librsync.spec
Update everything necessary in preparation for release of v2.3.2. Note CMakeLists.txt and TODO.md are already up to date. Also correct `CONTRIBUTING.md` release instructions for the right `html` path for doxygen docs.
=> Release v2.3.4.

.github/workflows/lint.yml, CMakeLists.txt
Fixes #262
I'm not sure avoiding transient includes is really a worthwhile migration here, so this just disables the check in CI.
I could also see an argument that we should either:
1. Remove it altogether
2. Refactor the headers so that `librsync.h` pulls in everything in the public API and underneath that there are no recursive includes
3. (Some other refactor?)
=> Disable IWYU in CI

.github/workflows/check.yml
The current v3 is failing in https://github.com/librsync/librsync/actions/runs/14822488795/job/41611359533#step:1:42 and apparently the update should fix this https://github.com/orgs/community/discussions/152695. I don't think we're relying on any behaviors that will break with the update. In particular, [v4 requires that the file names be unique](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) but we seem to already do that by including matrix parameters.
There are IWYU failures that seem unrelated (#262).
=> Update to upload-artifact@v4
